import React from 'react';

export default function ChatPDFSummaryModal({ isOpen, onClose, data, darkMode, t = {} }) {
  if (!isOpen || !data) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadFile = () => {
    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>BIS Mitra Official PDF Summary Report</title>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; color: #1e293b; background: #fff; }
    .header { background: #0f172a; color: #fff; padding: 24px; border-radius: 12px; margin-bottom: 24px; border-bottom: 4px solid #10b981; }
    .header h1 { margin: 0; font-size: 24px; font-weight: 800; color: #fff; }
    .header p { margin: 4px 0 0 0; color: #34d399; font-size: 14px; font-weight: 600; }
    .meta { display: flex; justify-content: space-between; font-size: 12px; color: #64748b; border-bottom: 1px solid #e2e8f0; padding-bottom: 12px; margin-bottom: 20px; }
    .box { background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 10px; padding: 16px; margin-bottom: 20px; }
    .box-title { font-size: 12px; font-weight: 800; text-transform: uppercase; color: #64748b; margin-bottom: 8px; }
    .question-text { font-size: 16px; font-weight: 700; color: #0f172a; margin: 0; }
    .answer-text { font-size: 15px; line-height: 1.6; color: #334155; white-space: pre-wrap; }
    .badge { display: inline-block; background: #ecfdf5; color: #065f46; border: 1px solid #a7f3d0; padding: 4px 10px; border-radius: 6px; font-size: 12px; font-weight: 700; margin-right: 8px; margin-bottom: 8px; }
    .footer { text-align: center; margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 16px; font-size: 12px; color: #94a3b8; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🇮🇳 BUREAU OF INDIAN STANDARDS (BIS) MITRA</h1>
    <p>Official AI Advisory & Regulatory Summary Report</p>
  </div>
  <div class="meta">
    <span>📅 Generated: ${new Date().toLocaleString('en-IN')}</span>
    <span>🔒 Official Verification Document</span>
    <span>Ref: BIS-MITRA-${Date.now().toString(36).toUpperCase()}</span>
  </div>

  <div class="box" style="border-left: 4px solid #3b82f6;">
    <div class="box-title">❓ Question Asked by User</div>
    <p class="question-text">${data.question || 'User Query'}</p>
  </div>

  <div class="box" style="border-left: 4px solid #10b981;">
    <div class="box-title">🛡️ BIS Official Advisory & Technical Summary</div>
    <div class="answer-text">${data.answer || ''}</div>
  </div>

  ${data.sources && data.sources.length > 0 ? `
  <div class="box">
    <div class="box-title">📑 Verified Indian Standards (IS) & Cited Sources</div>
    <div>
      ${data.sources.map(s => `<span class="badge">📌 ${typeof s === 'string' ? s : s.title || s.isCode || JSON.stringify(s)}</span>`).join('')}
    </div>
  </div>
  ` : ''}

  <div class="footer">
    <p>Generated by BIS Mitra AI Assistant — Official Bureau of Indian Standards Quality Portal</p>
    <p>Website: <strong>bis.gov.in</strong> | Emergency Consumer Portal: <strong>manakonline.in</strong></p>
  </div>
</body>
</html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `BIS_Mitra_Summary_${Date.now()}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const now = new Date();
  const dateStr = now.toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
  const timeStr = now.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
  const refCode = `BIS-MITRA-${Date.now().toString(36).toUpperCase()}`;

  const summaryPoints = (data.answer || '')
    .split('\n')
    .filter(line => line.trim().length > 10)
    .slice(0, 4);

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/75 backdrop-blur-sm p-4">
      <style>{`
        @media print {
          body > *:not(#chat-pdf-report-root) { display: none !important; }
          #chat-pdf-report-root { display: block !important; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: #fff !important; color: #000 !important; }
          .no-print { display: none !important; }
          .print-container { box-shadow: none !important; border: none !important; max-width: 100% !important; }
        }
      `}</style>
      <div id="chat-pdf-report-root" className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl max-h-[92vh] overflow-y-auto print-container text-slate-900">
        {/* Header */}
        <div className="bg-slate-900 text-white p-6 rounded-t-2xl border-b-4 border-emerald-500 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-emerald-500 text-white flex items-center justify-center text-2xl font-black shadow-md">
              🇮🇳
            </div>
            <div>
              <h2 className="text-xl sm:text-2xl font-black tracking-tight text-white">BUREAU OF INDIAN STANDARDS (BIS)</h2>
              <p className="text-emerald-400 text-xs sm:text-sm font-bold">BIS Mitra — Official AI Advisory & Regulatory PDF Summary Report</p>
            </div>
          </div>
          <button onClick={onClose} className="no-print text-slate-400 hover:text-white text-2xl font-bold p-1 cursor-pointer">✕</button>
        </div>

        {/* Content Body */}
        <div className="p-6 space-y-6">
          {/* Metadata Row */}
          <div className="flex flex-wrap items-center justify-between text-xs text-slate-500 border-b pb-3 gap-2">
            <span>📅 <strong>Date:</strong> {dateStr} at {timeStr}</span>
            <span>🔖 <strong>Ref No:</strong> <code className="bg-slate-100 px-1.5 py-0.5 rounded font-mono font-bold text-slate-700">{refCode}</code></span>
            <span className="text-emerald-700 font-bold bg-emerald-50 border border-emerald-300 px-2 py-0.5 rounded-md">✅ Verified BIS Knowledge Base</span>
          </div>

          {/* User Question Box */}
          <div className="bg-slate-900 text-slate-100 rounded-xl p-4 border border-slate-700 shadow-sm">
            <div className="font-bold text-xs uppercase tracking-wider text-emerald-400 mb-1">
              ❓ User Query / Question Asked:
            </div>
            <p className="text-lg font-bold text-white leading-snug">
              {data.question}
            </p>
          </div>

          {/* Key Summary Bullet Points */}
          <div className="bg-emerald-50 border-2 border-emerald-300 rounded-xl p-4">
            <div className="font-extrabold text-xs uppercase tracking-wider text-emerald-900 mb-2 flex items-center gap-1.5">
              <span>💡</span>
              <span>Executive Summary & Key Takeaways:</span>
            </div>
            <ul className="space-y-1.5 text-sm text-emerald-950 font-medium">
              {summaryPoints.map((pt, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-emerald-600 font-bold">•</span>
                  <span>{pt.replace(/^[\*•\-]\s*/, '')}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Full Official BIS Advisory Response */}
          <div className="bg-slate-50 border border-slate-200 rounded-xl p-5">
            <div className="font-bold text-xs uppercase tracking-wider text-slate-600 mb-3 flex items-center gap-1.5">
              <span>📖</span>
              <span>Full Official Technical Advisory & Detailed Answer:</span>
            </div>
            <div className="prose max-w-none text-slate-900 text-sm leading-relaxed whitespace-pre-wrap font-sans">
              {data.answer}
            </div>
          </div>

          {/* Sources Section */}
          {data.sources && data.sources.length > 0 && (
            <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
              <div className="font-bold text-xs uppercase tracking-wider text-blue-900 mb-2">
                🛡️ Applicable Indian Standards (IS Codes) & Verified Sources:
              </div>
              <div className="flex flex-wrap gap-2">
                {data.sources.map((src, i) => (
                  <span key={i} className="bg-white border border-blue-300 text-blue-900 text-xs font-bold px-2.5 py-1 rounded-lg shadow-2xs">
                    📌 {typeof src === 'string' ? src : src.title || src.isCode || JSON.stringify(src)}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Official Disclaimer */}
          <div className="border-t pt-4 text-center text-xs text-slate-500">
            <p className="font-semibold text-slate-700">Official Bureau of Indian Standards (BIS) Mitra Regulatory Document</p>
            <p className="mt-1">This report is synthesized from official BIS Gazette Notifications, Quality Control Orders (QCOs), and Indian Standards (IS Code registry).</p>
            <p className="mt-1 font-bold text-emerald-700">Verify official licenses & certificates at bis.gov.in / manakonline.in</p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="no-print flex flex-col sm:flex-row gap-3 p-4 border-t bg-slate-50 rounded-b-2xl">
          <button
            onClick={handlePrint}
            className="flex-1 bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-3 px-4 rounded-xl flex items-center justify-center gap-2 transition cursor-pointer shadow-md"
          >
            🖨️ Print / Save as PDF
          </button>
          <button
            onClick={handleDownloadFile}
            className="flex-1 bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded-xl flex items-center justify-center gap-2 transition cursor-pointer shadow-md"
          >
            📥 Download Summary Document
          </button>
          <button
            onClick={onClose}
            className="px-6 bg-slate-200 hover:bg-slate-300 text-slate-800 font-bold py-3 rounded-xl transition cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
